apiVersion: v1
kind: Service
metadata:
  name: currenttimeservice
spec:
  selector:
    app: currenttimeservice
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
